#Version := OxMetrics9
Version := OxMetrics8
OS := Windows

OX := "C:\Program Files\$(Version)\Ox\bin64\oxl.exe"
OXFLAGS := -DOX7 -v1 -d 
ECHO := echo
CD := dir
COPY := copy
OXDOC := "C:\Program Files (x86)\oxdoc\bin\oxdoc.bat"
SED := "C:\Program Files (x86)\GnuWin32\bin\sed.exe"
ERASE := erase
niq := ..\niqlow\include

